name: Milestone Task
description: "Use tasks for accomplish milestone"
title: "[Milestone task]: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **↑ Don't forget write about bug as short in title pls**
        **↑ タイトルに端的に内容について記載するのをお忘れなく！**

  - type: textarea
    id: about
    attributes:
      label: How it would to do to accomplish?
      description: |
        Write how the task would be to do.
        このタスクの実施内容を記載してください。
    validations:
      required: true

  - type: textarea
    id: howto
    attributes:
      label: What it should do to accomplish?
      description: |
        Write how the task should be for accomplish.
        このタスクの完了条件を記載してください。
    validations:
      required: true
