name: App Manual Deploy

on:
  workflow_dispatch: {}

jobs:
  Deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy
    permissions:
      contents: read
      deployments: write
      statuses: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: npm install && npm run build
        working-directory: ./astro
      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./astro/dist --project-name=skyshare
