name: App Manual Deploy

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
      - develop

jobs:
  get_env_name:
    uses: ./.github/workflows/get-environment-from-branch.yml

  deploy:
    needs: ["get_env_name"]
    environment:
      name: ${{ needs.get_env_name.outputs.env_name }}
    runs-on: ubuntu-latest
    name: Build & Deploy
    permissions:
      contents: read
      deployments: write
      statuses: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Build
        run: node --version; npm install && npm run build
        working-directory: ./astro
        env:
          PUBLIC_CREATEPAGES_ENDPOINT: ${{ secrets.PUBLIC_CREATEPAGES_ENDPOINT }}
          PUBLIC_DELETEPAGE_ENDPOINT: ${{ secrets.PUBLIC_DELETEPAGE_ENDPOINT }}
          PUBLIC_GETPAGES_ENDPOINT: ${{ secrets.PUBLIC_GETPAGES_ENDPOINT }}
          PUBLIC_IS_NOT_PRODUCTION: ${{ vars.PUBLIC_IS_NOT_PRODUCTION }}

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./astro/dist --project-name=skyshare
