name: Get Environment from branch Name

on:
  workflow_call:
    outputs:
      env_name:
        description: "Environment value"
        value: ${{ jobs.get_env_name.outputs.env_name }}

jobs:
  get_env_name:
    name: Get Environment from branch
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.get_env_name.outputs.env_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Output Environment value
        id: get_env_name
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "::set-output name=env_name::production"
          else
            echo "::set-output name=env_name::preview"
          fi